FROM python:3.12.7-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Alterar o diretório de trabalho para o diretório `app`
WORKDIR /app

# Instalar dependências
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

# Copiando o projeto para a imagem
ADD . /app

# Sincronizando o projeto
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

ENTRYPOINT []

EXPOSE 8501

CMD ["streamlit", "run", "app/dashboard/embedded_system.py"]
